############# English navigation ##############
# main menu
[[main]]
name = "About"
URL = "about/"
weight = 30

[[main]]
weight = 10
name = "IT Services"
hasChildren = true

  [[main]]
  parent = "IT Services"
  name = "Application Development"
  URL = "appdev/"

  [[main]]
  parent = "IT Services"
  name = "Blockchain Implementation"
  URL = "bcimpl/"

  [[main]]
  parent = "IT Services"
  name = "DevOps"
  URL = "devops/"

  [[main]]
  parent = "IT Services"
  name = "Application Support"
  URL = "appsupport/"

  [[main]]
  parent = "IT Services"
  name = "Cloud Infra Management"
  URL = "cloudinfra/"

  [[main]]
  parent = "IT Services"
  name = "Quality Testing & Automation"
  URL = "qta/"
  
  [[main]]
  parent = "IT Services"
  name = "MsgCloud - Bulk Whatsapp"
  URL = "msgcloud/"
  
  [[main]]
  parent = "IT Services"
  name = "Stock Market Trading Platform"
  URL = "stmp/"  
  
  [[main]]
  parent = "IT Services"
  name = "IoT & IT Asset Management"
  URL = "iotmon/"  
  
[[main]]
weight = 20
name = "Bio Solutions"
hasChildren = true

  [[main]]
  parent = "Bio Solutions"
  name = "Ecolly MicrobialX Compost"
  URL = "ecollymxc/"

  [[main]]
  parent = "Bio Solutions"
  name = "Ecolly MicrobialX Purifier"
  URL = "ecollymxp/"
  
[[main]]
weight = 21
name = "Green Energy"
hasChildren = true

  [[main]]
  parent = "Green Energy"
  name = "Portable Power Generator"
  URL = "gexfinite/"
  
[[main]]
weight = 22
name = "Data Center Services"
hasChildren = true

  [[main]]
  parent = "Data Center Services"
  name = "Dedicated Server"
  URL = "computeserver/"  
 
  [[main]]
  parent = "Data Center Services"
  name = "AI Compute Server"
  URL = "aicomputeserver/"  
  
[[main]]
weight = 23
name = "Skill University"
hasChildren = true

  [[main]]
  parent = "Skill University"
  name = "Elitical Education"
  URL = "skill/"  
 
 
#[[main]]
#name = "Blog"
#URL = "blog/"
#weight = 50

[[main]]
name = "Contact"
URL = "contact/"
weight = 40

[[footer]]
name = "Contact us"
URL = "contact/"

[[footer]]
name = "Terms and Conditions"
URL = "tnc/"

[[footer]]
name = "Privacy Policy"
URL = "pp/"

[[footer]]
name = "Data Policy"
URL = "dp/"

[[footer]]
name = "About"
URL = "about/"

[[footer]]
name = "GDPR"
URL = "gdprdata/"

[[footer]]
name = "Payment Refund"
URL = "refundpolicy/"

[[footer]]
name = "Shipping and Delivery"
URL = "shipdelivery/"

